FROM node:16-slim

ARG PORT=3000
ARG FRONTEND_URL="http://localhost:8080"

# install pnpm
RUN corepack enable && corepack prepare pnpm@7.0.0 --activate

USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY --chown=node:node . .

ENV TZ=Europe/Berlin
ENV NODE_ENV=production
ENV PORT=${PORT}

EXPOSE ${PORT}
CMD [ "node", "src/server/index.js" ]
